[tool.poetry]
name = "bgf-de-project"
version = "0.1.0"
description = ""
authors = ["Erman Torun <etorun@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
dbt-bigquery = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
